[id='rest_v2_cluster_stop']
= Stopping {brandname} Clusters
Shut down entire {brandname} clusters with `POST` requests.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cluster?action=stop
----

{brandname} responds with `200(OK)` and then performs an orderly shutdown of
the entire cluster.


[id='rest_v2_stop_cluster_server']
= Stopping Specific {brandname} Servers in Clusters
Shut down one or more specific servers in {brandname} clusters with `GET`
requests and the `?action=stop&server` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cluster?action=stop&server={server1_host}&server={server2_host}
----

{brandname} responds with `200(OK)`.

[id='rest_v2_backup_cluster']
= Create a Backup of {brandname} cluster content
Initiate the creation of a backup file (application/zip) containing all resources (Caches, Cache configurations, Counters, Proto schemas, Scripts)
that are currently stored in the  cluster's cache container(s). The created backup file can then be retrieved via a subsequent
link:#rest_v2_backup_manager_get[GET] operation.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cluster/backups/{backupName}
----

Requests may optionally include a JSON payload that contains various parameters for the backup operation.

.Json Parameters

|===
|Key |Required or Optional |Value

|`directory`
|OPTIONAL
|The path of a directory on the server that should be used to create and ultimately store the backup file.

|===

[id='rest_v2_backup_cluster_list']
= Get Backup Names
Retrieve the names of all backups that are in progress, completed or in a failed state.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cluster/backups
----

[id='rest_v2_backup_cluster_head']
= Checking Backup availability
Verify that a backup operation has completed. A 200 response means that the resource is available, whereas 202
indicates that the initial backup operation is still in progress.

[source,options="nowrap",subs=attributes+]
----
HEAD /rest/v2/cluster/backups/{backupName}
----

[id='rest_v2_backup_cluster_get']
= Downloading a Backup file
Download a completed backup file from the server. A 200 response means that the resource is available, whereas 202
indicates that the initial backup operation is still in progress.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cluster/backups/{backupName}
----

[id='rest_v2_backup_cluster_delete']
= Deleting a Backup file
Delete a Backup from the {brandname} server. A 204 response means that the Backup has been deleted immediately, whereas
a 202 response indicates that the backup is still in progress and the created file will be deleted once the backup has
completed.

[source,options="nowrap",subs=attributes+]
----
DELETE /rest/v2/cluster/backups/{backupName}
----

[id='rest_v2_restore_cluster']
= Restore {brandname} cluster content
Restore content from a Backup file.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cluster?action=restore
----

[NOTE]
The uploaded backup file must contain a container corresponding to `{cacheManagerName}` in order for the containers content
to be restored.

Supported content types:

application/json::
To be used if the backup file is already available on the server.

.JSON Parameters

|===
|Key |Required or Optional |Value

|`location`
|REQUIRED
|The path of the backup file to be restored.

|`resources`
|OPTIONAL
|A JSON object specifying the resources to include in the backup. If no resources are specified, then all
resources are included in the backup. If one or more resource types are specified, then only the specified resources
are included.

|===

include::backup_resources.adoc[]

The following example shows how to restore all counters from a backup file already located on the server.

[source,json,options="nowrap",subs=attributes+]
----
include::json_examples/rest_backup_restore_request_body.json[]
----

multipart/form-data::
The backup zip file to be uploaded to the server and then restored.

.Form Data
|===
|Parameter |Content-Type |Required or Optional |Value

|`backup`
|`application/zip`
|REQUIRED
|The bytes of the backup file to be restored.
|===

.Example Request
----
Content-Type: multipart/form-data; boundary=5ec9bc07-f069-4662-a535-46069afeda32
Content-Length: 7798

--5ec9bc07-f069-4662-a535-46069afeda32
Content-Disposition: form-data; name="backup"; filename="testManagerRestoreParameters.zip"
Content-Type: application/zip
Content-Length: 7353

<zip-bytes>
--5ec9bc07-f069-4662-a535-46069afeda32--
----
