name: Synchronize changes to the website

on:
  push:
    branches:
      - 'gh-actions'
    paths:
      - 'documentation/**'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build docs with Maven
      run: mvn install -Pdistribution -pl documentation -am -s maven-settings.xml

    - name: Clone infinispan.github.io
      uses: actions/checkout@master
      with:
        repository: infinispan/infinispan.github.io
        ref: master
        path: infinispan.github.io

    - name: Show me
      run: |
        ls -1
        ls documentation

    - if: github.ref == 'refs/heads/gh-actions'
      name: Copy docs to dev
      run: |
        cp -r documentation/target/generated/1*/html/* infinispan.github.io/docs/dev/

    - name: Commit and push changes
      run: |
        cd infinispan.github.io
        git config --global user.email "dnaro@redhat.com"
        git config --global user.name "dnaro"
        git add . --all
        git commit -m "Synchronized docs from infinispan ${{ github.ref }}"
        git push origin master
