name: Synchronize changes to the website

on:
  push:
    branches:
      - 'fix-docs-synch'
    paths:
      - 'documentation/**'

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Maven Action
      uses: setup-maven-action@latest
      with:
        java-version: 17
        maven-version: 3.9.0

    - name: Build docs with Maven
      run: mvn install -Pdistribution -pl documentation -am -s maven-settings.xml
